# Generated by Django 3.1.4 on 2020-12-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lastname',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
