# Generated by Django 3.1.4 on 2020-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201225_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='xd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default='xd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='about',
            field=models.TextField(),
        ),
    ]
