# Generated by Django 3.1.4 on 2020-12-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201225_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.series'),
        ),
    ]
