# Generated by Django 3.1.4 on 2020-12-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201225_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='webapp.training'),
        ),
    ]
