# Generated by Django 3.1.4 on 2020-12-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20201225_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.TextField(blank=True),
        ),
    ]
