# Generated by Django 3.1.4 on 2020-12-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20201225_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
