# Generated by Django 3.1.4 on 2020-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20201226_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(default='x', max_length=30),
            preserve_default=False,
        ),
    ]
