# Generated by Django 3.1.4 on 2020-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20201226_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
