# Generated by Django 3.1.4 on 2020-12-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20201226_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
