# Generated by Django 3.1.4 on 2021-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20201228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='yt_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
