# Generated by Django 3.1.4 on 2021-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20210101_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='about',
            field=models.CharField(blank=True, default='No about', max_length=1000),
        ),
    ]
